Repository amuletml/amulet, pull requests merged in 2018-02, with the labels that each got.

#6 Skolem Type Constants
  examples/church-lists.ml
  examples/skolems.ml
  src/Control/Monad/Infer.hs
  src/Core/Lower.hs
  src/Core/Optimise.hs
  src/Core/Optimise/Inline.hs
  src/Core/Simplify.hs
  src/Errors.hs
  src/Syntax.hs
  src/Syntax/Raise.hs
  src/Syntax/Resolve.hs
  src/Syntax/Subst.hs
  src/Types/Infer.hs
  src/Types/Kinds.hs
  src/Types/Unify.hs
  src/Types/Wellformed.hs
Labels: enhancement, help wanted

#8 Improve Pretty
  src/Backend/Lua.hs
  src/Control/Monad/Infer.hs
  src/Data/Span.hs
  src/Errors.hs
  src/Pretty.hs
  src/Syntax.hs
Labels: enhancement

#9 Detect ambiguous references in the resolver
  examples/ambiguity.ml
  src/Errors.hs
  src/Syntax/Resolve.hs
  src/Syntax/Resolve/Scope.hs
Labels: enhancement

#10 Use type-directed lowering
  src/Core/Lower.hs
  src/Core/Optimise/Inline.hs
Labels: enhancement

#5 Modules
  examples/modules.ml
  src/Control/Monad/Infer.hs
  src/Core/Core.hs
  src/Core/Lower.hs
  src/Errors.hs
  src/Parser.y
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Parser/Wrapper.hs
  src/Syntax.hs
  src/Syntax/Resolve.hs
  src/Syntax/Resolve/Scope.hs
  src/Syntax/Resolve/Toplevel.hs
  src/Types/Infer.hs
  src/Types/Unify.hs
  src/Types/Wellformed.hs
Labels: enhancement, good first issue
