Repository amuletml/amulet, pull requests merged in 2019-12, with the labels that each got.

#238 Feature: "Lua static" backend
  amuletml.cabal
  bin/Amc.hs
  bin/Amc/Compile.hs
  bin/Amc/Compile/Raw.hs
  bin/Amc/Compile/Shim.hs
  src/Text/Pretty/Semantic.hs
  tests/amc/usage.t
  tools/deploy-build.sh
Labels: Backend, enhancement

#244 Abstract out Backend.Lua.Emit's graph handling
  amuletml.cabal
  bin/Amc/Repl.hs
  src/Backend/EmitGraph.hs
  src/Backend/Lua/Emit.hs
  src/Backend/Scheme.hs
  src/Core/Arity.hs
  src/Core/Builtin.hs
  src/Core/Core.hs
  src/Core/Free.hs
  src/Core/Lint.hs
  src/Core/Lower.hs
  src/Core/Lower/Basic.hs
  src/Core/Lower/Pattern.hs
  src/Core/Lower/TypeRepr.hs
  src/Core/Occurrence.hs
  src/Core/Optimise.hs
  src/Core/Optimise/CommonExpElim.hs
  src/Core/Optimise/DeadCode.hs
  src/Core/Optimise/Reduce.hs
  src/Core/Optimise/Reduce/Base.hs
  src/Core/Optimise/Reduce/Inline.hs
  src/Core/Optimise/Reduce/Pattern.hs
  src/Core/Optimise/Sinking.hs
  src/Core/Optimise/Uncurry.hs
  src/Core/Types.hs
Labels: Backend, aesthetics

#246 unfeature: Remove Chicken Scheme backend
  amuletml.cabal
  bin/Amc.hs
  bin/Amc/Compile.hs
  bin/Amc/Repl/Eval.hs
  bin/AmuletLsp/Features.hs
  lib/amulet/base.ml
  lib/amulet/base/scheme.ml
  lib/amulet/exception.ml
  lib/base.ss
  lib/prelude.ml
  lib/scheme/condition.ml
  lib/scheme/conversion.ml
  lib/scheme/io.ml
  src/Backend/Lua/Emit.hs
  src/Backend/Lua/Postprocess.hs
  src/Backend/Scheme.hs
  src/CompileTarget.hs
  src/Core/Core.hs
  src/Core/Free.hs
  src/Core/Lint.hs
  src/Core/Lower.hs
  src/Core/Occurrence.hs
  src/Core/Optimise/CommonExpElim.hs
  src/Core/Optimise/DeadCode.hs
  src/Core/Optimise/Reduce.hs
  src/Core/Optimise/Sinking.hs
  src/Language/Lua/Syntax.hs
  src/Parser.y
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Syntax/Desugar.hs
  src/Syntax/Resolve.hs
  src/Syntax/Toplevel.hs
  src/Syntax/Verify.hs
  src/Types/Infer.hs
  tests/amc/usage.t
  tests/driver/Test/Core/Backend.hs
  tools/deploy-build.sh
Labels: Chicken Backend

#247 Add support for dot-op assignments
  lib/array.ml
  src/Parser.y
  tests/parser/pass_dotop_assign.ml
  tests/parser/pass_dotop_assign.out
Labels: Parser, enhancement

#248 Use CSS grid in examples instead
  bin/GenExample.hs
Labels: Infra, enhancement

#251 Implement the "Static Argument" transformation
  amuletml.cabal
  src/Core/Optimise.hs
  src/Core/Optimise/SAT.hs
  src/Core/Simplify.hs
  tests/lua/monoid.lua
  tests/lua/nested_match.lua
  tests/lua/nested_match_basic.lua
  tests/lua/opt_sat.lua
  tests/lua/opt_sat.ml
  tests/lua/opt_sat_unsat.lua
  tests/lua/opt_sat_unsat.ml
  tests/lua/pattern_guard.lua
Labels: Optimiser, enhancement

#253 Add support for -Werror and friends
  bin/Amc.hs
  bin/Amc/Compile.hs
  src/Frontend/Errors.hs
  tests/amc/usage.t
Labels: enhancement
