Repository amuletml/amulet, pull requests merged in 2019-10, with the labels that each got.

#177 Feature: Associated Type Families
  src/Control/Monad/Chronicles.hs
  src/Control/Monad/Infer.hs
  src/Data/Reason.hs
  src/Parser.y
  src/Syntax/Desugar.hs
  src/Syntax/Resolve.hs
  src/Syntax/Resolve/Toplevel.hs
  src/Syntax/Toplevel.hs
  src/Syntax/Types.hs
  src/Types/Infer.hs
  src/Types/Infer/Class.hs
  src/Types/Kinds.hs
  tests/resolve/pass_class.out
  tests/types/begin02.out
  tests/types/begin03.out
  tests/types/class/assoc-missing.ml
  tests/types/class/assoc-missing.out
  tests/types/class/assoc01.ml
  tests/types/class/assoc01.out
  tests/types/class/assoc02.ml
  tests/types/class/assoc02.out
  tests/types/class/assoc03.ml
  tests/types/class/assoc03.out
  tests/types/class/default01.out
  tests/types/class/default03.out
  tests/types/class/fundep04.out
  tests/types/class/mtpc-scope.out
  tests/types/class/superclass.out
Labels: dependent-amulet, enhancement

#178 Differentiate between user-provided and temporary variables
  compiler/Repl.hs
  src/Backend/Escape.hs
  src/Backend/Lua/Builtin.hs
  src/Backend/Lua/Emit.hs
  src/Control/Monad/Infer.hs
  src/Control/Monad/Namey.hs
  src/Core/Builtin.hs
  src/Core/Lint.hs
  src/Core/Lower.hs
  src/Core/Lower/Basic.hs
  src/Core/Optimise.hs
  src/Core/Var.hs
  src/Syntax/Builtin.hs
  src/Syntax/Desugar.hs
  tests/lua/as_pattern.lua
  tests/lua/emit_ifs.lua
  tests/lua/lazy.lua
  tests/lua/let_pattern.lua
  tests/lua/list.lua
  tests/lua/match_heuristic.lua
  tests/lua/match_multi.lua
  tests/lua/monoid.lua
  tests/lua/nested_match.lua
  tests/lua/nested_match_basic.lua
  tests/lua/newtype.lua
  tests/lua/op_apply.lua
  tests/lua/opt_constant_fold.lua
  tests/lua/opt_single_match.lua
  tests/lua/optimise_sink.lua
  tests/lua/pattern_guard.lua
  tests/lua/pattern_multiple_consume.lua
  tests/lua/precedence.lua
  tests/lua/recursive_defaults.lua
  tests/lua/section.lua
  tests/lua/stream-zip.lua
  tests/lua/values_occ.lua
Labels: enhancement

#181 Add idiom brackets
  compiler/Errors.hs
  examples/pipe.ml
  src/Core/Core.hs
  src/Data/Reason.hs
  src/Parser.y
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Syntax/Desugar.hs
  src/Syntax/Expr.hs
  src/Syntax/Expr/Instances.hs
  src/Syntax/Let.hs
  src/Syntax/Resolve.hs
  src/Syntax/Transform.hs
  src/Syntax/Value.hs
  src/Syntax/Verify.hs
  tests/lua/emit_ifs.ml
  tests/lua/list.lua
  tests/lua/stream-zip.ml
  tests/lua/stream.ml
  tests/parser/fail_pattern_guard.out
  tests/types/idioms.ml
  tests/types/idioms.out
Labels: aesthetics, enhancement

#182 Yet Another Module System
  amuletml.cabal
  compiler/Errors.hs
  compiler/Main.hs
  compiler/Prove.hs
  compiler/Repl.hs
  compiler/Test/Core/Backend.hs
  compiler/Test/Core/Lint.hs
  compiler/Test/Syntax/Resolve.hs
  compiler/Test/Syntax/Verify.hs
  compiler/Test/Types/Check.hs
  examples/modules.ml
  src/Core/Lower.hs
  src/Core/Lower/Basic.hs
  src/Data/Reason.hs
  src/Frontend/Driver.hs
  src/Frontend/Errors.hs
  src/Parser.y
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Syntax/Builtin.hs
  src/Syntax/Desugar.hs
  src/Syntax/Expr.hs
  src/Syntax/Resolve.hs
  src/Syntax/Resolve/Error.hs
  src/Syntax/Resolve/Import.hs
  src/Syntax/Resolve/Scope.hs
  src/Syntax/Resolve/Toplevel.hs
  src/Syntax/Toplevel.hs
  src/Syntax/Toplevel.hs-boot
  src/Syntax/Var.hs
  src/Syntax/Verify.hs
  src/Types/Infer.hs
  tests/resolve/fail_unresolved_module.ml
  tests/resolve/fail_unresolved_module.out
  tests/resolve/pass_modules.out
Labels: enhancement, good first issue

#190 Lots of minor improvements to the module system
  compiler/Main.hs
  compiler/Repl.hs
  src/Control/Monad/Chronicles.hs
  src/Frontend/Driver.hs
  src/Frontend/Errors.hs
  src/Syntax/Resolve/Error.hs
Labels: Yet Another Module System, bug

#192 Switch the argument parser to be sub-command based
  compiler/Main.hs
  compiler/Repl.hs
Labels: enhancement

#200 Lower and Lint bug blitz
  .travis.yml
  examples/mini-servant.ml
  repl.sh
  src/Control/Monad/Infer.hs
  src/Types/Infer.hs
  src/Types/Infer/Class.hs
  src/Types/Unify.hs
  tests/driver/Test/Types/Check.hs
  tests/lint/shadow_forall.ml
  tests/lua/section.lua
  tests/lua/section.ml
  tests/types/begin05.ml
  tests/types/begin05.out
  tests/types/fail_value_restriction.ml
  tests/types/fail_value_restriction2.ml
  tests/types/fail_value_restriction2.out
  tests/types/unify.ml
Labels: X-Core Lint, bug

#203 Quick Look Impredicativity
  amuletml.cabal
  src/Syntax/Pretty.hs
  src/Types/Infer.hs
  src/Types/Infer.hs-boot
  src/Types/Infer/App.hs
  src/Types/Infer/Builtin.hs
  src/Types/Infer/Class.hs
  src/Types/Kinds.hs
  src/Types/Unify.hs
  tests/lua/default-method.lua
  tests/lua/list.lua
  tests/lua/monoid.lua
  tests/lua/nested_match.lua
  tests/lua/op_apply.lua
  tests/lua/stream-zip.lua
  tests/lua/values_occ.lua
  tests/types/class/constraint-category.out
  tests/types/class/default02-fail.out
  tests/types/class/fundep01.out
  tests/types/class/fundep02.out
  tests/types/class/row-cons-fail.out
  tests/types/gadt/dict02-fail.out
  tests/types/gadt/fail_term.out
  tests/types/gadt/fin.out
  tests/types/idioms.out
  tests/types/nasty_cycle.out
  tests/types/rankn/impredicative01-fail.out
  tests/types/rankn/impredicative01-pass.ml
  tests/types/rankn/impredicative01-pass.out
  tests/types/rankn/ql-impredicative.ml
  tests/types/rankn/ql-impredicative.out
  tests/types/rankn/ql-impredicative02.ml
  tests/types/rankn/ql-impredicative02.out
  tests/types/rankn/ql-impredicative03.ml
  tests/types/rankn/ql-impredicative03.out
  tests/types/rankn/ql-impredicative04.ml
  tests/types/rankn/ql-impredicative04.out
  tests/types/rankn/ql-impredicative05.ml
  tests/types/rankn/ql-impredicative05.out
  tests/types/rankn/ql-impredicative06.ml
  tests/types/rankn/ql-impredicative06.out
  tests/types/rankn/req-fail.out
Labels: TC, enhancement

#206 Tiny module-system and CLI improvements
  bin/Amc.hs
  bin/Amc/Repl.hs
  bin/GenExample.hs
  src/Control/Monad/Infer.hs
  src/Core/Simplify.hs
  src/Frontend/Driver.hs
  tests/amc/files/import.ml
  tests/amc/lib/my_lib.ml
  tests/amc/lib/prelude.ml
  tests/amc/path.t
  tests/amc/prelude.t
  tests/amc/usage.t
  tests/driver/Test/Core/Backend.hs
  tests/driver/Test/Core/Lint.hs
  tests/driver/Test/Syntax/Resolve.hs
  tests/driver/Test/Types/Check.hs
Labels: Yet Another Module System, enhancement

#207 Feature: 'include' statement
  repl.sh
  src/Core/Lower.hs
  src/Parser.y
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Syntax/Desugar.hs
  src/Syntax/Resolve.hs
  src/Syntax/Toplevel.hs
  src/Syntax/Verify.hs
  src/Types/Infer.hs
  tests/resolve/pass_include.ml
  tests/resolve/pass_include.out
Labels: Yet Another Module System, enhancement

#208 Add `typeable`
  amuletml.cabal
  lib/amulet/option.ml
  lib/amulet/typeable.ml
  lib/prelude.ml
  src/Backend/Lua/Builtin.hs
  src/Backend/Lua/Emit.hs
  src/Control/Monad/Infer.hs
  src/Core/Arity.hs
  src/Core/Builtin.hs
  src/Core/Lower.hs
  src/Parser.y
  src/Parser/Context.hs
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Syntax/Builtin.hs
  src/Syntax/Desugar.hs
  src/Syntax/Implicits.hs
  src/Syntax/Resolve.hs
  src/Syntax/Toplevel.hs
  src/Syntax/Type.hs
  src/Syntax/Types.hs
  src/Syntax/Verify.hs
  src/Types/Derive/Typeable.hs
  src/Types/Derive/Typeable.hs-boot
  src/Types/Infer.hs
  src/Types/Infer/Class.hs
  src/Types/Infer/Pattern.hs
  src/Types/Kinds.hs
  src/Types/Unify.hs
  src/Types/Unify/Equality.hs
  src/Types/Unify/Trace.hs
  tests/lua/default-method.lua
  tests/lua/monoid.lua
  tests/lua/promotion.lua
  tests/lua/promotion.ml
  tests/lua/stream-zip.lua
  tests/lua/values_occ.lua
  tests/resolve/pass_import_paths.out
  tests/types/class/constraint-category.out
  tests/types/class/fundep01.out
  tests/types/class/typeable-arrow.ml
  tests/types/class/typeable-arrow.out
  tests/types/idioms.out
  tests/types/rankn/ql-impredicative-lots.out
  tests/types/rankn/rankn02-pass.ml
  tests/types/rankn/rankn02-pass.out
  tests/types/typeable-fail.ml
  tests/types/typeable-fail.out
  tests/types/typeable.ml
  tests/types/typeable.out
Labels: TC, TC: Type Classes, enhancement

#209 Small improvements to `Cast'.
  .ghci
  src/Backend/Lua/Emit.hs
  src/Core/Builtin.hs
  src/Core/Core.hs
  src/Core/Free.hs
  src/Core/Lint.hs
  src/Core/Lower.hs
  src/Core/Occurrence.hs
  src/Core/Optimise.hs
  src/Core/Optimise/DeadCode.hs
  src/Core/Optimise/Newtype.hs
  src/Core/Optimise/Reduce.hs
  src/Core/Optimise/Reduce/Inline.hs
  src/Core/Optimise/Sinking.hs
  src/Core/Types.hs
  tests/lua/let_pattern.lua
  tests/lua/monoid.lua
  tests/lua/nested_match.lua
  tests/lua/stream-zip.lua
  tests/lua/stream.lua
  tests/lua/values_occ.lua
Labels: enhancement

#210 Run newtype optimisation as part of lower
  amuletml.cabal
  bin/Amc.hs
  src/Core/Lower.hs
  src/Core/Lower/Basic.hs
  src/Core/Lower/Pattern.hs
  src/Core/Lower/TypeRepr.hs
  src/Core/Optimise/Newtype.hs
  src/Core/Simplify.hs
  tests/lua/monoid.lua
  tests/lua/promotion.lua
Labels: X-soundness, bug

#211 Module caching
  amuletml.cabal
  bin/Amc.hs
  bin/Amc/Repl.hs
  bin/GenExample.hs
  src/Frontend/Driver.hs
Labels: Yet Another Module System, enhancement
