Repository amuletml/amulet, pull requests merged in 2020-01, with the labels that each got.

#256 sortBy -> sort_by
  lib/amulet/list.ml
Labels: Standard Library

#257 Move the C shim into a separate file
  .gitignore
  amuletml.cabal
  bin/Amc/Compile/Raw.hs
  bin/Amc/Compile/Shim.c
  bin/Amc/Compile/Shim.hs
Labels: bug

#261 add a library of stream functions
  lib/data/stream.ml
  lib/prelude.ml
Labels: Standard Library, enhancement

#262 Add range syntax
  examples/amulet-logo.ml
  examples/lists.ml
  lib/data/enumeration.ml
  lib/data/stream.ml
  src/Data/Reason.hs
  src/Parser.y
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Syntax/Desugar.hs
  src/Syntax/Expr.hs
  src/Syntax/Expr/Instances.hs
  src/Syntax/Let.hs
  src/Syntax/Resolve.hs
  src/Syntax/Transform.hs
  src/Syntax/Value.hs
  src/Syntax/Verify.hs
  src/Types/Infer.hs
  tests/driver/Test/Types/Holes.hs
Labels: enhancement

#263 Change begin → struct, and begin → do, and begin → begin
  .ghci
  lib/amulet/base.ml
  lib/amulet/base/lua.ml
  lib/lua/bit.ml
  src/Parser.y
  src/Parser/Context.hs
  src/Parser/Lexer.x
  src/Parser/Token.hs
  src/Syntax/Desugar.hs
  tests/lexer/context/do.ml
  tests/lexer/context/do.out
  tests/lexer/context/module.ml
  tests/lexer/context/module.out
  tests/lua/begin_monad.ml
  tests/lua/begin_wrapper.ml
  tests/lua/stream-zip.ml
  tests/parser/fail_pattern_guard.out
  tests/resolve/fail_let_open_struct.ml
  tests/resolve/fail_let_open_struct.out
  tests/resolve/nested_qual.ml
  tests/resolve/pass_include.ml
  tests/types/begin01.ml
  tests/types/begin01.out
  tests/types/begin02.ml
  tests/types/begin03.ml
  tests/types/begin04.ml
  tests/types/begin04.out
  tests/types/begin05.ml
  tests/types/begin05.out
  tests/types/class/orphan-soundness.ml
  tests/types/scope.ml
Labels: Parser, enhancement

#267 Use stack install to copy binary files
  tools/deploy-build.sh
Labels: Infra, bug
